### ISSUE TITLE
In low-latency, the current line segment being drawn flickers when the stylus pen is lifted.

### ISSUE THREAD

**Issue by hongtao1019** [android/large-screen-codelabs#7]
In FastRenderer, lifting the stylus pen triggers a write to the double buffer, i.e., it triggers the onDrawDoubleBufferedLayer method callback. At this point, the current line segment being drawn will flicker. Could you please explain the specific reason for this?

**Comment by hongtao1019** [comment]
fix

**Comment by hongtao1019** [comment]
fix

**Comment by indieexplore** [comment]
> In FastRenderer, lifting the stylus pen triggers a write to the double buffer, i.e., it triggers the onDrawDoubleBufferedLayer method callback. At this point, the current line segment being drawn will flicker. Could you please explain the specific reason for this?

Well done! And how to fix this?

**Comment by hongtao1019** [comment]
> > In FastRenderer, lifting the stylus pen triggers a write to the double buffer, i.e., it triggers the onDrawDoubleBufferedLayer method callback. At this point, the current line segment being drawn will flicker. Could you please explain the specific reason for this?
> 
> Well done! And how to fix this?

use [1.0.0-alpha04](https://mvnrepository.com/artifact/androidx.graphics/graphics-core/1.0.0-alpha04)
